---
# tasks file for demo
- debug:
    msg: "group: {{ ec2_tag_group }} "

- name: run runClient.sh for Producer
  shell: ./runClient.sh
  args:
    chdir: /home/ubuntu/ndnrtc
  when: ec2_tag_group  == "ndnrtc-producer" 

- name: run runClient.sh for Consumers
  shell: ./runClient.sh
  args:
    chdir: /home/ubuntu/ndnrtc
  when: ec2_tag_group  == "ndnrtc-consumer" 

