---
# tasks file for producer-gw

- name: do an ndnping from producer to WU to make sure face is there
  #shell: "/usr/bin/ndnping -c 5 /ndn/edu/wustl >& /dev/null"
  shell: "/usr/bin/ndnping -c 5 /ndn/edu/wustl "
  when: ec2_tag_group is defined and ((ec2_tag_group == "ndnrtc-producer") or (ec2_tag_group == "validated-image-producer"))

- local_action: copy content="{{ inventory_hostname }}" dest=./producer_hostname
  when: ec2_tag_group is defined and ((ec2_tag_group == "ndnrtc-producer") or (ec2_tag_group == "validated-image-producer"))

- name: copy producer_hostname file to WU
  copy: dest=/home/ndnops/producer_hostname src=./producer_hostname owner=ndnops mode=644
  when: inventory_hostname == "WU"

- name: copy nfdc command file to WU
  copy: dest=/home/ndnops/nfdcCommand.sh src=roles/producer-gw/files/nfdcCommand.sh owner=ndnops mode=755
  when: inventory_hostname == "WU"

- name: run nfdc command file on WU
  shell: ./nfdcCommand.sh 
  args: 
    chdir: /home/ndnops
  when: inventory_hostname == "WU"


