---
## This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
  
  roles:
  - {role: 'NOC', tags: 'NOC'}  # to use the tag, use this option: --tags "NOC"
  - {role: 'nfd_host', tags: 'nfd_host'}  # to use the tag, use this option: --tags "nfd_host"
  - {role: 'ndnrtc', tags: 'ndnrtc'}  # to use the tag, use this option: --tags "ndnrtc"


