---
## This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
  
  roles:
#  - {role: 'NOC', tags: 'NOC'}  # to use the tag, use this option: --tags "NOC"
#  - {role: 'nfd_host', tags: 'nfd_host'}  # to use the tag, use this option: --tags "nfd_host"
#  - {role: 'hila-ndntools', tags: 'hila-ndntools'}  # to use the tag, use this option: --tags "hila-ndntools"
  - {role: 'validation', tags: 'validation'}   # to use the tag, use this option: --tags "validation"
  - {role: 'producer-gw', tags: 'producer-gw'}   # to use the tag, use this option: --tags "producer-gw"



