---
# Provision instances in AWS specific to the LAMP HA Proxy demo
- name: Provision instances in AWS
  hosts: localhost
  connection: local
  gather_facts: False

  # load AWS variables from this group vars file
  vars_files:
  - group_vars/aws_vars_jdd
  - group_vars/all

  tasks:
  # Launch End Hosts for each NDN Testbed gateway node

  - name: Launch end host for WU
    ec2:
      access_key: "{{ ec2_access_key }}"
      secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ ec2_keypair }}"
      group: "{{ ec2_security_group }}"
      type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image_wu }}"
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 20
          delete_on_termination: true
      region: "{{ ec2_region_wu }}"
      instance_tags: "{'host_gw':'{{ ec2_host_gw_wu }}' ,'host_gw_prefix':'{{ ec2_host_gw_prefix_wu }}' ,'ansible_group':'wu_host', 'type':'{{ ec2_instance_type }}', 'group':'validated-image-producer', 'Name':'wu_host_''{{ local_user_name }}'}"
      count: "{{ ec2_host_count }}"
      wait: true
    register: ec2

  - name: Launch end host for ARIZONA
    ec2:
      access_key: "{{ ec2_access_key }}"
      secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ ec2_keypair }}"
      group: "{{ ec2_security_group }}"
      type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image_arizona }}"
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 20
          delete_on_termination: true
      region: "{{ ec2_region_arizona }}"
      instance_tags: "{'host_gw':'{{ ec2_host_gw_arizona }}' ,'host_gw_prefix':'{{ ec2_host_gw_prefix_arizona }}' , 'ansible_group':'arizona_host', 'type':'{{ ec2_instance_type }}', 'group':'validated-image-consumer', 'Name':'arizona_host_''{{ local_user_name }}'}"
      count: "{{ ec2_host_count }}"
      wait: true
    register: ec2

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"
