---
## This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
  
  roles:
  - {role: 'producer-gw', tags: 'producer-gw'}   # to use the tag, use this option: --tags "producer-gw"
  - {role: 'demo_chunks', tags: 'demo_chunks'}  # to use the tag, use this option: --tags "demo_chunks"


