---
## This playbook terminates all instances

# Apply common configuration to all hosts
- name: remove face on WU gw for producers
  hosts: WU
  roles:
  - {role: 'producer-gw-destroy-face', tags 'producer-gw-destroy-face'} 

- name: terminate tagged instances
  hosts: all
  tasks:
    - ec2_facts:
      when: inventory_hostname != "WU"

    - ec2:
        state: 'absent'
        region: "{{ ec2_region }}"
        #instance_ids: "{{ ansible_ec2_instance_id }}"
        instance_ids: "{{ ec2_id }}"
      delegate_to: localhost
      when: inventory_hostname != "WU"

